### ISSUE TITLE
Are REQ/RES only used for Actions?

### ISSUE THREAD

**Issue by mistresseve666** [moleculer-framework/protocol#1]
Howdy,

Since I see there are dedicated topics for Events, are the REQ and RES topics *only* used for actions? Or is there anything else that uses them?

Thanks,
-robodude666

**Comment by icebob** [comment]
REQ/RES are for action calling.

**Comment by mistresseve666** [comment]
Exclusively? If any other REQ/RES mechanism is required in the future, will dedicated topics be added for them to the protocol, or will these be reused?

**Comment by icebob** [comment]
Yes. If need other types of communication, we will create new topics.
